auth:
  type: github
  github:
    clientId: "y0urg1thubc1ient1d"
    clientSecret: "an0ther1ongs3cretstr1ng"
    callbackUrl: "http://JHUB_HOST/hub/oauth_callback"
  admin:
    access: true
    users:
      - thiagoalmeidasa

